FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
ENV LANG C.UTF-8

ENV DEBIAN_FRONTEND=noninteractive

# 安装所需依赖
RUN apt-get update
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.9 python3-pip
RUN apt-get update && apt-get install -y git wget net-tools

# 创建软链接
RUN ln -s /usr/bin/python3.9 /usr/bin/python

# 安装特定版本 paddlepaddle-gpu
COPY whl/paddlepaddle_gpu-2.4.2.post117-cp39-cp39-linux_x86_64.whl .
RUN python -m pip install --upgrade pip && pip install paddlepaddle_gpu-2.4.2.post117-cp39-cp39-linux_x86_64.whl

COPY requirements-gpu.txt .
RUN pip --default-timeout=100 install -r requirements-gpu.txt --index-url https://mirror.baidu.com/pypi/simple/ \
    --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple/\nhttps://mirrors.aliyun.com/pypi/simple/\nhttps://pypi.douban.com/simple/

# timezone设置
ENV TZ=Asia/Shanghai
RUN apt-get update \
    && apt-get -y install -y tzdata \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata

WORKDIR /app

COPY . /app
# 创建日志目录
RUN mkdir -p logs

# RUN chmod +x /app/run.sh
# CMD ["sh", "-c", "export PATH=${PATH}:$PATH; /app/run.sh"]
CMD ["python", "server.py"]
